"""ADIF export."""

from __future__ import annotations

import datetime as dt
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from .. import __version__
from ..core import bands, modes
from ..core.dto import QsoRow

ADIF_VERSION = "3.1.4"
PROGRAM_ID = "hamrlog"

#: Digital values exported as application defined fields.
APP_FIELD_PREFIX = "APP_HAMRLOG_"

#: ADIF PROP_MODE values for contacts that did not go out direct.
PROP_MODE_REPEATER = "RPT"
PROP_MODE_ECHOLINK = "ECH"


def _field(name: str, value: Any) -> str:
    """Render one ADIF field, or an empty string when there is no value.

    The declared length counts characters, as the ADI specification requires.
    """
    if value is None:
        return ""
    text = str(value).strip()
    if not text:
        return ""
    return f"<{name.upper()}:{len(text)}>{text}"


def qso_to_adif(row: QsoRow, *, station: dict[str, str] | None = None) -> str:
    """Serialise one contact as an ADI record terminated by ``<EOR>``.

    A contact made through a repeater is a split frequency QSO: ADIF defines
    FREQ as the logging station's transmit frequency and FREQ_RX as what it
    listens on. So FREQ carries the repeater input and FREQ_RX its output,
    and PROP_MODE is set to RPT.
    """
    mode = modes.get(row.mode)
    adif_mode = mode.adif_mode if mode else (row.mode or "")
    adif_submode = mode.adif_submode if mode else ""

    # Transmit frequency first, receive frequency only when they differ.
    tx_hz = row.freq_tx_hz or row.freq_hz
    rx_hz = row.freq_hz if row.freq_tx_hz and row.freq_tx_hz != row.freq_hz else None

    parts = [
        _field("CALL", row.call),
        _field("QSO_DATE", row.qso_utc.strftime("%Y%m%d")),
        _field("TIME_ON", row.qso_utc.strftime("%H%M%S")),
        _field("BAND", row.band),
        _field("FREQ", bands.frequency_mhz(tx_hz)),
        _field("FREQ_RX", bands.frequency_mhz(rx_hz)),
        _field("MODE", adif_mode),
        _field("SUBMODE", adif_submode),
        _field("RST_SENT", row.rst_sent),
        _field("RST_RCVD", row.rst_rcvd),
        _field("NAME", row.name),
        _field("QTH", row.qth),
        _field("GRIDSQUARE", row.gridsquare),
        _field("COUNTRY", row.country),
        _field("COMMENT", row.comment),
        _field("OPERATOR", row.operator_callsign),
        _field("STATION_CALLSIGN", row.operator_callsign),
    ]

    if station:
        parts += [
            _field("MY_RIG", station.get("rig", "")),
            _field("MY_ANTENNA", station.get("antenna", "")),
            _field("TX_PWR", station.get("power_w", "")),
            _field("MY_GRIDSQUARE", station.get("gridsquare", "")),
            _field("MY_CITY", station.get("qth", "")),
        ]

    if row.via_repeater:
        prop_mode = PROP_MODE_ECHOLINK if row.mode == "ECHOLINK" else PROP_MODE_REPEATER
        parts.append(_field("PROP_MODE", prop_mode))
        parts.append(_field(f"{APP_FIELD_PREFIX}REPEATER", row.repeater_call))

    # Application fields keep hamrlog specific data round-trippable.
    parts.append(_field(f"{APP_FIELD_PREFIX}ENTRY_MODE", row.entry_mode))
    if row.station_name:
        parts.append(_field(f"{APP_FIELD_PREFIX}STATION", row.station_name))
    if row.mode and mode and row.mode != adif_mode:
        parts.append(_field(f"{APP_FIELD_PREFIX}MODE", row.mode))
    for key, value in sorted((row.digital_data or {}).items()):
        parts.append(_field(f"{APP_FIELD_PREFIX}{key}", value))

    return "".join(part for part in parts if part) + "<EOR>"


def adif_header(count: int) -> str:
    """ADI header block, ending with ``<EOH>``."""
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d %H%M%S")
    lines = [
        f"ADIF export generated by {PROGRAM_ID} {__version__}",
        _field("ADIF_VER", ADIF_VERSION),
        _field("PROGRAMID", PROGRAM_ID),
        _field("PROGRAMVERSION", __version__),
        _field("CREATED_TIMESTAMP", stamp),
        _field(f"{APP_FIELD_PREFIX}QSO_COUNT", count),
        "<EOH>",
    ]
    return "\n".join(lines) + "\n"


def write_adif_file(
    path: str | Path,
    rows: Iterable[QsoRow],
    *,
    stations: dict[str, dict[str, str]] | None = None,
) -> int:
    """Write contacts to an ADI file.

    Args:
        path: Destination file.
        rows: Contacts to export.
        stations: Optional map of station name to rig details, so MY_RIG and
            MY_ANTENNA can be filled per contact.

    Returns:
        Number of records written.
    """
    rows = list(rows)
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(adif_header(len(rows)))
        for row in rows:
            station = (stations or {}).get(row.station_name)
            handle.write(qso_to_adif(row, station=station) + "\n")
    return len(rows)
